Repository insightsengineering/rlistings, pull requests merged in 2022-12, with the labels that each got.

#56 Reorder source files
  R/rlistings.R
  R/rlistings_methods.R
  man/listing_methods.Rd
  man/paginate_listing.Rd
Labels: enhancement, sme

#66 Add unit tests for key cols
  tests/testthat/test-paginate_listing.R
Labels: documentation, sme

#70 Update staged_dependencies.yaml
  staged_dependencies.yaml
Labels: sme
