Repository insightsengineering/rlistings, pull requests merged in 2022-11, with the labels that each got.

#35 Update README
  NEWS.md
  README.Rmd
  README.md
  inst/WORDLIST
  vignettes/rlistings.Rmd
Labels: documentation, sme

#51 Enable checks for `workflow_dispatch` event
  .github/workflows/check.yaml
Labels: sme

#29 Add DSL01 and DSL02 regression tests
  NEWS.md
  tests/testthat/test-listing_dsl01.R
Labels: sme

#50 Example and file/imports reorganization
  DESCRIPTION
  NEWS.md
  R/paginate_listing.R
  R/rlistings-package.R
  R/rlistings.R
  inst/WORDLIST
  man/figures/lifecycle-archived.svg
  man/figures/lifecycle-defunct.svg
  man/figures/lifecycle-deprecated.svg
  man/figures/lifecycle-experimental.svg
  man/figures/lifecycle-maturing.svg
  man/figures/lifecycle-questioning.svg
  man/figures/lifecycle-stable.svg
  man/figures/lifecycle-superseded.svg
  man/listing_methods.Rd
  man/listings.Rd
  man/paginate_listing.Rd
  man/rlistings-package.Rd
  tests/runtests.R
  tests/testthat.R
  tests/testthat/setup.R
  tests/testthat/test-listing_dsl01.R
  tests/testthat/test-listings.R
  tests/testthat/test-paginate_listing.R
  vignettes/rlistings.Rmd
Labels: enhancement, sme
