Repository insightsengineering/rlistings, pull requests merged in 2023-05, with the labels that each got.

#113 Adding complete tests for wrapping in pagination and export
  NAMESPACE
  R/rlistings_methods.R
  man/listing_methods.Rd
  tests/testthat/test-paginate_listing.R
  tests/testthat/test-print.R
Labels: bug, enhancement, sme

#118 Fixing pagination tests for CRAN by specifying `hsep = "-"`
  tests/testthat/test-paginate_listing.R
  tests/testthat/test-print.R
Labels: bug, sme, test :rotating_light:

#124 `export_as_txt` refactoring
  DESCRIPTION
  NAMESPACE
  R/listing_export.R
  R/paginate_listing.R
  R/rlistings.R
  man/defunct.Rd
  man/export_as_txt.Rd
  man/paginate.Rd
  man/reexports.Rd
  tests/testthat/test-paginate_listing.R
Labels: sme

#125 Release v0.2.2 [skip vbump]
  DESCRIPTION
  NEWS.md
  README.md
Labels: sme
