Repository insightsengineering/rlistings, pull requests merged in 2023-09, with the labels that each got.

#151 Fix NEWS version [skip vbump]
  NEWS.md
Labels: sme

#139 Adds min package version
  .github/workflows/scheduled.yaml
  DESCRIPTION
  NEWS.md
Labels: core

#160 Add `teal.modules.clinical` as downstream dependency
  staged_dependencies.yaml
Labels: sme

#158 Allow custom formats, `NA` values in key columns
  NEWS.md
  R/rlistings.R
  tests/testthat/test-listings.R
Labels: bug, sme
