Repository insightsengineering/rlistings, pull requests merged in 2023-10, with the labels that each got.

#161 [skip vbump] rlistings release v0.2.5
  DESCRIPTION
  NEWS.md
Labels: sme, release

#162 Close #155 and add test for export_as_txt
  NEWS.md
  R/paginate_listing.R
  tests/testthat/_snaps/export.md
  tests/testthat/test-export.R
  tests/testthat/test-paginate_listing.R
Labels: sme

#163 Fixes after wrap_string refactoring
  R/rlistings.R
  R/rlistings_methods.R
  tests/testthat/_snaps/print.md
  tests/testthat/test-print.R
Labels: bug, sme

#167 fix vec_nlines and complete support newline character
  NEWS.md
  R/rlistings_methods.R
  tests/testthat/_snaps/print.md
  tests/testthat/test-print.R
Labels: bug, enhancement, sme

#170 adding tests to fix infinite loop and export_as_txt colwidths that were hidden
  tests/testthat/_snaps/print.md
  tests/testthat/test-print.R
Labels: bug, sme, priority

#172 Update logo
  README.md
  man/figures/rlistings.png
Labels: sme, blocked

#175 Fix lint, apply styler
  R/rlistings.R
  man/matrix_form-listing_df-method.Rd
  tests/testthat/test-listings.R
  vignettes/rlistings.Rmd
Labels: sme

#177 Pagination vignette
  vignettes/pagination.Rmd
  vignettes/rlistings.Rmd
Labels: sme

#180 Fix bug in `add_listing_col` when specifying a function and a format
  NEWS.md
  R/rlistings.R
  tests/testthat/test-listings.R
Labels: sme

#181 Column formatting vignette
  inst/WORDLIST
  vignettes/col_formatting.Rmd
  vignettes/rlistings.Rmd
Labels: sme
