Repository insightsengineering/rlistings, pull requests merged in 2023-02, with the labels that each got.

#82 Doc updates
  .github/workflows/check.yaml
  NEWS.md
  R/paginate_listing.R
  R/rlistings.R
  R/rlistings_methods.R
  inst/WORDLIST
  man/listing_methods.Rd
  man/listings.Rd
  man/paginate_listing.Rd
  tests/testthat/test-listings.R
Labels: documentation, sme

#92 fix version bump [skip vbump]
  DESCRIPTION
  NEWS.md
Labels: bug, sme

#88 dsl01 test will go into scda.test
  staged_dependencies.yaml
  tests/testthat/test-listing_dsl01.R
Labels: enhancement, sme, test :rotating_light:

#93 Closes #43 - adding page-size machinery
  NAMESPACE
  NEWS.md
  R/paginate_listing.R
  R/rlistings.R
  inst/WORDLIST
  man/listings.Rd
  man/paginate.Rd
  man/paginate_listing.Rd
  tests/testthat/helper-rlistings.R
  tests/testthat/test-paginate_listing.R
Labels: enhancement
