Repository insightsengineering/rlistings, pull requests merged in 2024-06, with the labels that each got.

#214 Changes from fork PR for truetype font
  DESCRIPTION
  NEWS.md
  R/paginate_listing.R
  R/rlistings.R
  R/rlistings_methods.R
  inst/WORDLIST
  man/listing_methods.Rd
  man/make_row_df-listing_df-method.Rd
  man/matrix_form-listing_df-method.Rd
  man/paginate.Rd
  man/vec_nlines.Rd
  tests/testthat/setup.R
  tests/testthat/test-matrix_form.R
  tests/testthat/test-paginate_listing.R
Labels: enhancement, sme, collab

#212 Bumps `{rmarkdown}` minimal version
  DESCRIPTION
Labels: core

#217 update description and news [skip vbump]
  DESCRIPTION
  NEWS.md
  R/rlistings.R
  R/rlistings_methods.R
  man/listing_methods.Rd
  man/matrix_form-listing_df-method.Rd
Labels: sme
